
# 146 ansible all -m yum -a "name=git state=present" -b
# 153 ansible all -m git -a "dest=/var/www/html repo=https://github.com/ravi2krishna/ecomm.git" -b

---
- name: Deploy Ecomm App
  hosts: n1
  become: yes

  tasks:
  - name: Install GIT
    yum:
      name: git
      state: present
   
  - name: Deploy App
    git:
      dest: /var/www/html 
      repo: https://github.com/ravi2krishna/ecomm.git
    
...
